  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[footer]]
  name = "Hosted on Github Pages"
  weight = 1
  identifier = "Hosted on Github Pages"
  url = "https://github.com"